# fly.toml app configuration file generated for hydrangea-todo on 2023-07-19T16:59:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hydrangea-todo"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
